### ISSUE TITLE
USDS Web Design Standards Gem

### ISSUE THREAD

**Issue by dydx** [RichardLitt/octobuild#19]
I'd like to create a rails gem that functions similarly to Thoughtbot's [Refills](https://github.com/thoughtbot/refills) gem, but for the recently published U.S Digital Services Web Design Standards

https://github.com/dydx/usds-wds

**Comment by RichardLitt** [comment]
Nice! That sounds awesome. 

Anything you could use help on?

**Comment by dydx** [comment]
I'm not sure just yet. If I run into anything I'll mention it here.

**Comment by RichardLitt** [comment]
:+1:

**Comment by RichardLitt** [comment]
@dydx Hey! How did you do?

**Comment by dydx** [comment]
Objectively, I got it working about 60%-- it can import the gem assets and whatnot, but a lot of work came up and I neglected to iron out a few details.

Thanks for putting on the contest!

**Comment by RichardLitt** [comment]
No worries! 60% is still pretty good. Finish it!

**Comment by RichardLitt** [comment]
Thanks for joining us! Closing until next year's run. :)
