### ISSUE TITLE
npm-janitor 

### ISSUE THREAD

**Issue by hemanth** [RichardLitt/octobuild#20]
http://h3manth.com/npm-janitor/

**Comment by RichardLitt** [comment]
This is a great project! Wow. I have so many flags I am missing.

**Comment by simonv3** [comment]
:+1:

I already feel bad about the sparse packages I've published on NPM :P

This would be really cool to do with general github projects. Look for things like contributing.md, readme.md, etc. 

Edit: reminds me to continue working on this: https://github.com/opensourcedesign/foss-contributors-checklist

**Comment by hemanth** [comment]
:angel:

**Comment by RichardLitt** [comment]
Hey! How did this turn out?

**Comment by hemanth** [comment]
It's still going on, there are few dependent packages that needs fixes.

**Comment by RichardLitt** [comment]
Good luck!

**Comment by RichardLitt** [comment]
Thanks for joining us! Closing until next year's run. :)
