### ISSUE TITLE
Fit Schedule

### ISSUE THREAD

**Issue by myfashionhub** [RichardLitt/octobuild#22]
A Google calendar-integrated app that helps users book and keep track of all their fitness classes.
https://github.com/myfashionhub/fit-schedule

**Comment by simonv3** [comment]
Cool! Definitely let me or @RichardLitt know if you want any feedback, thoughts, etc. 

Or just general :+1:s

**Comment by RichardLitt** [comment]
Nice! This is really cool.

**Comment by RichardLitt** [comment]
Hey! How did this turn out, @myfashionhub?

**Comment by myfashionhub** [comment]
@RichardLitt I got a lot done but it's still in progress

**Comment by RichardLitt** [comment]
Cool! I'm glad. Feel free to ping if you need help. :)

**Comment by RichardLitt** [comment]
Thanks for joining us! Closing until next year's run. :)
