### ISSUE TITLE
The Dragon; a short story

### ISSUE THREAD

**Issue by RichardLitt** [RichardLitt/octobuild#26]
I'm writing a depressing short story. I want it to be done by the end of October.

**Comment by simonv3** [comment]
:+1:

**Comment by RichardLitt** [comment]
4,000 words done so far. Getting there.

**Comment by simonv3** [comment]
10,000 words your goal?

**Comment by RichardLitt** [comment]
No. Just 1000 words a day.

**Comment by simonv3** [comment]
That is awesome, until the end of October? (or whenever you deem it done?)

**Comment by RichardLitt** [comment]
Until I deem it done. It might be a long while. Right now I have 2 of at least 5 different chapters done. They'll probably need to be rewritten.

**Comment by RichardLitt** [comment]
I didn't finish. :( But I worked on it! :)

**Comment by RichardLitt** [comment]
Thanks for joining us! Closing until next year's run. :)
