### ISSUE TITLE
QuakeBot

### ISSUE THREAD

**Issue by simonv3** [RichardLitt/octobuild#27]
Follow QuakeBot to be told if there's an earthquake happening near you.

https://github.com/simonv3/quakebot

**Comment by RichardLitt** [comment]
Woo!

**Comment by RichardLitt** [comment]
How did this go, @simonv3?

**Comment by simonv3** [comment]
Well it works - but it's not running http://simonv3.github.io/quakebot/

It's not running because Webfaction flipped out when I started running it. I need to figure out hosting for it - I've applied for the Knight Foundation grant and that would pretty much cover that :P If there's other grants anyone knows of, I could apply for those as well.

**Comment by RichardLitt** [comment]
Nice!

**Comment by RichardLitt** [comment]
Thanks for joining us! Closing until next year's run. :)
